apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapplication22-deployment
  labels:
    app: WebApplication22
spec:
  replicas: 1
  selector:
    matchLabels:
      app: WebApplication22  
  template:
    metadata:
      labels:
        app: WebApplication22
    spec:
      containers:
      - name: mydnazurecr0705
        image: mydnazurecr0705.azurecr.io/azurecontainerrepo001:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: webapisvcsecret
---
apiVersion: v1
kind: Service
metadata:
  name: webapplication22svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: WebApplication22
